### ISSUE TITLE
Exception looking up a word with `!definition`

### ISSUE THREAD

**Issue by OrangeTacTics** [OrangeTacTics/chairmanmao#117]
`!definition 策略`

gives the error:

```
2021-11-02 19:01:45 INFO OrangeTacTics#0949: definition()
Ignoring exception in command definition:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chairmanmao-x59jzYI8-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/projects/chairmanmao/chairmanmao/cogs/comrade.py", line 55, in cmd_definition
    definitions = await self.api.lookup_word(word)
  File "/root/projects/chairmanmao/chairmanmao/api.py", line 305, in lookup_word
    results = await self.client.named_query(
  File "/root/projects/chairmanmao/chairmanmao/api_client.py", line 41, in named_query
    return await self.query(query, variables)
  File "/root/projects/chairmanmao/chairmanmao/api_client.py", line 36, in query
    raise Exception(res_json["errors"])
Exception: [{'message': 'Not a valid syllable: lu:e4', 'locations': [{'line': 13, 'column': 9}], 'path': ['dict', 0, 'zhuyin']}]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/chairmanmao-x59jzYI8-py3.8/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/chairmanmao-x59jzYI8-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/.cache/pypoetry/virtualenvs/chairmanmao-x59jzYI8-py3.8/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Exception: [{'message': 'Not a valid syllable: lu:e4', 'locations': [{'line': 13, 'column': 9}], 'path': ['dict', 0, 'zhuyin']}]
```

**Comment by OrangeTacTics** [comment]
The zhuyin was broken. I had to convert the pinyin to accented so dragonmapper could understand it.
